name = "miku-tools"
type = "webpack"
account_id = ""
workers_dev = true

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "pnpm install --no-frozen-lockfile && pnpm run generate"
output_dir = "dist"

[build.environment]
NODE_VERSION = "16"
PNPM_VERSION = "8.7.1"