name = "miku-tools"
type = "webpack"
account_id = ""
workers_dev = true

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "npm install --legacy-peer-deps && npm run generate"
output_dir = "dist"

[build.environment]
NODE_VERSION = "18.17.1"